# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=12)),
                ('description', models.CharField(max_length=1000)),
                ('dateTopic', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
