# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='autor',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='topic',
            name='description',
            field=models.CharField(max_length=1000),
        ),
    ]
