# ACHIEVEMENT TYPE FIELD.
ACHIEVEMENT_TYPE = ((1, 'Exercício Correto'),
                    (2, 'Resposta no Fórum'),
                    (3, 'Pontuação do Usuário'),
                    (4, 'Submissão de Exercícios'))
CORRECT_EXERCISE_ACHIEVEMENTS = 1
SUBMITED_ANSWERS_ACHIEVEMENTS = 2
SCORE_ACHIEVEMENTS = 3
SUBMITED_EXERCISE_ACHIEVEMENTS = 4


# NAME FIELD.
MAX_LENGTH_NAME = 35

# DESCRIPTION FIELD.
MAX_LENGTH_DESCRIPTION = 100

# DEFAULT VALUE FOR ACHIEVEMENT ICON FIELD.
ACHIEVEMENTE_IMAGE = "Trophy-96.png"
