# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 00:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverpasswordprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2017, 4, 30)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2017, 4, 30)),
        ),
    ]
