# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 00:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_scored'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='scored',
            new_name='score',
        ),
    ]
