# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-18 02:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20170416_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoverpasswordprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2017, 4, 18)),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2017, 4, 18)),
        ),
    ]
