# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 19:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20170421_1940'),
        ('user', '0006_auto_20170422_0112'),
    ]

    operations = [
    ]
