# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 00:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20170422_1118'),
        ('user', '0008_merge_20170422_1908'),
    ]

    operations = [
    ]
