# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-23 00:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_merge_20170422_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverpasswordprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2017, 4, 22)),
        ),
    ]
