# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 00:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name_plural': 'Perfil de Usuario'},
        ),
        migrations.AddField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='CodaMais/core/static/user/user_default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='key_expires',
            field=models.DateTimeField(default=datetime.date(2017, 4, 6)),
        ),
    ]
