# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170406_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='CodaMais/core/media/user/user_default.png', editable=False, upload_to=''),
        ),
    ]
