# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-02 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.PositiveIntegerField(choices=[(1, 'Básico'), (2, 'Condicional'), (3, 'Repetição'), (4, 'Array'), (5, 'Ponteiro')])),
                ('text', models.TextField()),
                ('score', models.PositiveIntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('deprecated', models.PositiveIntegerField(choices=[(0, 'Não'), (1, 'Sim')])),
            ],
        ),
    ]
