# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='input_exercise',
            field=models.CharField(default='ASD', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='output_exercise',
            field=models.CharField(default='DSA', max_length=1000),
            preserve_default=False,
        ),
    ]
