# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0002_auto_20170427_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexercise',
            name='scored',
            field=models.BooleanField(default=False),
        ),
    ]
