# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 21:33
from __future__ import unicode_literals

from django.db import migrations
import redactor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0003_auto_20170406_0118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='image',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='text',
        ),
        migrations.AddField(
            model_name='exercise',
            name='statement_question',
            field=redactor.fields.RedactorField(default='ASD', verbose_name='Text'),
            preserve_default=False,
        ),
    ]
