# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 00:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0004_auto_20170407_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='category',
            field=models.PositiveIntegerField(choices=[(1, 'Básico'), (2, 'Intermediário'), (3, 'Avançado')]),
        ),
    ]
