# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0005_auto_20170408_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='input_exercise',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='output_exercise',
            field=models.TextField(max_length=1000),
        ),
    ]
