# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-09 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0006_auto_20170408_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='input_exercise',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='output_exercise',
            field=models.CharField(max_length=1000),
        ),
    ]
