# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0008_auto_20170414_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexercise',
            name='number_submission',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userexercise',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
