# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0009_auto_20170414_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='userexercise',
            name='time',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
