# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0010_userexercise_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_exercise', models.CharField(max_length=1000)),
                ('output_exercise', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='test_cases',
            field=models.ManyToManyField(to='exercise.TestCase'),
        ),
    ]
