# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 23:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0011_auto_20170414_2350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='test_cases',
        ),
        migrations.AddField(
            model_name='testcase',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exercise.Exercise'),
            preserve_default=False,
        ),
    ]
