# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0012_auto_20170414_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='input_exercise',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='output_exercise',
        ),
        migrations.RemoveField(
            model_name='testcase',
            name='exercise',
        ),
        migrations.AddField(
            model_name='exercise',
            name='test_cases',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exercise.TestCase'),
            preserve_default=False,
        ),
    ]
