# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 00:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0013_auto_20170415_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='test_cases',
        ),
    ]
