# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 00:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0014_remove_exercise_test_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exercise.Exercise'),
            preserve_default=False,
        ),
    ]
