# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-15 00:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0015_testcase_exercise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='exercise.Exercise'),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input_exercise',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='output_exercise',
            field=models.TextField(max_length=1000),
        ),
    ]
