# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 01:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0016_auto_20170415_0030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestCase',
            new_name='TestCaseExercise',
        ),
    ]
