# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-22 01:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercise', '0017_auto_20170422_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userexercise',
            name='time',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
