# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import redactor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('content', redactor.fields.RedactorField(verbose_name='Text')),
            ],
        ),
    ]
