# TITLE FIELD.
MAX_LENGTH_TITLE = 200

# DESCRIPTION FIELD.
MAX_LENGTH_SUBTITLE = 500

# AUTHOR FIELD.
MAX_LENGTH_AUTHOR = 200

# DESCRIPTION FIELD.
MAX_LENGTH_DESCRIPTION = 1000

# RESPONSE CODES.
REQUEST_SUCCEEDED = 200  # 200 is return with success response.
