# TITLE FIELD.
MAX_LENGTH_TITLE = 200
MIN_LENGTH_TITLE = 5
TITLE_SIZE = 'Title must be between 5 and 200 characters'

# DESCRIPTION FIELD.
MAX_LENGTH_SUBTITLE = 500
MIN_LENGTH_SUBTITLE = 5
SUBTITLE_SIZE = 'Subtitle must be between 5 and 200 characters'

# AUTHOR FIELD.
MAX_LENGTH_AUTHOR = 12

# TOPIC DESCRIPTION FIELD.
MAX_LENGTH_TOPIC_DESCRIPTION = 100000000
MIN_LENGTH_TOPIC_DESCRIPTION = 10
TOPIC_DESCRIPTION_SIZE = 'Topic description must be between 10 and 100000000 characters'

# ANSWER DESCRIPTION FIELD.
MAX_LENGTH_ANSWER_DESCRIPTION = 100000000
MIN_LENGTH_ANSWER_DESCRIPTION = 10
ANSWER_DESCRIPTION_SIZE = 'Answer description must be between 10 and 100000000 characters'

# ERROR MESSAGES
INEXISTENT_TOPIC_ASSERT = "Topic does not have an author."
INEXISTENT_ANSWER_ASSERT = "Answer does not have an author."
INEXISTENT_REQUEST_USER = "The request user return NULL"
INEXISTENT_TOPIC = "The topic is NULL"

# ANSWER DESCRIPTION
ANSWER_DESCRIPTION_NAME = 'description'

# DEFAULT LOGGER
DEFAULT_LOGGER = 'default'
