# TITLE FIELD.
MAX_LENGTH_TITLE = 200

# DESCRIPTION FIELD.
MAX_LENGTH_SUBTITLE = 500

# AUTHOR FIELD.
MAX_LENGTH_AUTHOR = 12

# DESCRIPTION FIELD.
MAX_LENGTH_DESCRIPTION = 1000


# ERROR MESSAGES
DELETE_TOPIC_ASSERT = "Topic does not have an author."
