# CATEGORY FIELD.
CATEGORY_CHOICES = ((1, 'Básico'),
                    (2, 'Intermediário'),
                    (3, 'Avançado'))

# DEPRECATED FIELD.
DEPRECATED_CHOICES = ((0, 'Não'), (1, 'Sim'),)

# TITLE FIELD.
MAX_LENGTH_TITLE = 200

# DEPRECATED FIELD.
IS_NOT_DEPRECATED = 0

# INPUT FIELD.
MAX_LENGTH_INPUT = 1000

# OUTPUT FIELD.
MAX_LENGTH_OUTPUT = 1000

# RESPONSE CODES.
REQUEST_SUCCEEDED = 200
